name-template: 'v$RESOLVED_VERSION 🌟'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels: ['feature', 'enhancement']
  - title: '🐛 Bug Fixes'
    labels: ['fix', 'bugfix', 'bug']
  - title: '🧰 Maintenance'
    labels: ['chore', 'dependencies']

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

version-resolver:
  major:
    labels: ['major', 'breaking']
  minor:
    labels: ['minor', 'feature']
  patch:
    labels: ['patch', 'fix', 'bugfix', 'bug', 'chore']
  default: patch

template: |
  ## Changes
  $CHANGES

  ## Installation
  ```bash
  npm run install:all
  npm run dev
  ```
