name: Continuous Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      version:
        description: 'Version to deploy'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version }}

      - name: Deploy to ${{ github.event.inputs.environment }}
        run: |
          echo "🚀 Deploying to ${{ github.event.inputs.environment }} environment..."
          echo "📦 Version: ${{ github.event.inputs.version }}"
          echo "✅ Deployment completed successfully!"
          echo "🌐 Application available at: https://${{ github.event.inputs.environment }}.yourapp.com"
